#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
	sysctl -q -w net.netfilter.nf_conntrack_acct=1 2>/dev/null || true
	procd_open_instance
	procd_set_param command /usr/bin/ucode /usr/sbin/autoaddd
	procd_set_param respawn 3600 5 5
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	nft delete table inet autoadd 2>/dev/null
}

service_triggers() {
	procd_add_reload_trigger autoadd
}
